version: '3.9'

services:
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - '6379:6379'
  web:
    build: .
    command: bash -c "alembic upgrade head&& uvicorn main:app --host 0.0.0.0 --port 3000 --reload && python utils/seeder.py --count 1 "
    volumes:
      - .:/app
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - db
    links:
    - "db:pgsql-server"

  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file:
      - .env
    volumes:
    - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432

  celery_worker:
    container_name: celery_worker
    build: .
    command: celery -A utils.celery_worker.celery worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - web
      - redis

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "5050:80"
    env_file:
      - .env
    volumes:
    - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
    links:
    - "db:pgsql-server"
volumes:
  postgres_data:
  pgadmin-data: