version: '3.9'

services:
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - '6379:6379'

  web:
    build: .
    command: bash -c "alembic upgrade head&& uvicorn main:app --host 0.0.0.0 --port 3000 --reload && python utils/seeder.py --count 1 "
    volumes:
      - .:/app
    ports:
      - 3000:3000
    env_file:
      - .env
    # environment:
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=password
    #   - POSTGRES_DB=post_db
    #   - DATABASE_URL=postgresql+asyncpg://postgres:password@db:5432/post_db
    #   - SECRET_KEY=89023f0j2039jf90jkakmciumcses9mcs99mcs93c48ym72tmarf737mc7h47wna4c8791289h8f1h3f8h376fh8bf4
    depends_on:
      - db
    links:
    - "db:pgsql-server"

  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    # environment:
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=password
    #   - POSTGRES_DB=post_db
    #   - PGDATA = /var/lib/postgresql/data
    env_file:
      - .env
    volumes:
    - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432

  celery_worker:
    container_name: celery_worker
    build: .
    command: celery -A utils.celery_worker.celery worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    # environment:
    #   - CELERY_BROKER_URL=redis://redis:6379/0
    #   - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    # environment:
    #   - PGADMIN_DEFAULT_EMAIL=pgadmin@pgadmin.org
    #   - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    env_file:
      - .env
    volumes:
    - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
    links:
    - "db:pgsql-server"
volumes:
  postgres_data:
  pgadmin-data: